[nix] refactor out machine-specific code

diff --git a/nix/mynix b/nix/mynix
--- a/nix/mynix
+++ b/nix/mynix
@@ -1,10 +1,8 @@
 #!/usr/bin/env nix-shell
 #! nix-shell -i bash -p dmidecode
 
-
-# Shows the output of every command
-set +x
-set +e
+# Exit if command fails
+set -e
 
 HOME_MANAGER_VERSION=20.09
 machines["MacBookPro11,5"]=boston.nix
@@ -60,7 +58,9 @@ install() {
 
 refresh() {
   system_refresh
-  hm_refresh
+  if [ $? == 0 ]]; then
+    hm_refresh
+  fi
   exit $?
 }
 
